baseurl = "/"
languageCode = "en-us"
title = "Matt Chaib's blog"
theme = "hugo-xmin"
googleAnalytics = "UA-133774948-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."
    footer = "[Matt Chaib](https://www.mattchaib.com) 2019 | [Github](https://github.com/mogs-git) | [Twitter](https://twitter.com/mattchaib)"
