---
title: Text Mining the EU withdrawal bill Hansard
author: Matt Chaib
date: '2019-02-05'
slug: text-mining-the-eu-withdrawal-bill-hansard
categories:
  - Hansard Text Analysis
  - R
tags:
  - text analysis
  - politics
---



<div id="hansard-text-analysis-part-2" class="section level1">
<h1>Hansard Text Analysis (Part 2)</h1>
<p>This article will explore how text mining can be used to gather data from Parliamentary transcripts (Hansards). This will build on ideas from another article I wrote: if you haven’t read the first part, find that <a href="../../04/hansard-text-analysis-part-1/">here</a>. I will again lean heavily on methods I learned from <a href="https://juliasilge.com/">Julia Silge</a> and <a href="http://varianceexplained.org/about/">David Robinson</a> in their book <a href="https://www.tidytextmining.com/">Text mining with R</a> and the <a href="https://cran.r-project.org/web/packages/tidytext/vignettes/tidytext.html">tidytext</a> package. Be sure to use the Parliament glossary <a href="https://www.parliament.uk/site-information/glossary/">here</a> for tricky phrases.</p>
<p>What does text-mining analysis look like? Usually we have a set of related documents (e.g. news articles about different businesses) known as a <em>corpus</em>. Often, these articles don’t come in a format immediately appropriate for analysis so will first have to be “cleaned” and “standardised”, but we will ignore that for now. Every text mining analysis then seeks to convert features of the text into numerical values. This is just a fancy way of saying: first, we need to count things.</p>
<p>But what’s our goal here? What information can we “mine” from the text that you can’t get from just reading it? The first goal is summarisation. We can condense information down and extract the most important parts in a way that can be easily scaled. The second goal is clarification. When you read a debate, you have certain intuitions and feelings about what went on. “Those three spoke about similar things”. “He was the most aggressive”. We want to quantify these things, and by putting numbers on them make statements in a statistically rigorous, evidence-based way. We can make unbiased searches for every pattern in the text, even ones that people might miss after a few readings. The third goal for lots of text mining work is prediction. You have gathered information on what is there, and maybe you can use this again in the future to predict something in another text? This is a bit beyond the scope of this article, but an example might be using the data you have gathered from one set of speeches to predict the party of a speaker in a new speech.</p>
<p>The approaches used here are useful for another simple reason: automation. Letting a program collect some of the available data for us is much faster and more accurate than doing things by hand.</p>
<p>Let’s start with what we can count. This will act as an outline for the rest of the article:</p>
<ul>
<li>Total number of words (per speech)</li>
<li>Number of individual words</li>
<li>Number of other grammatical features of the text (punctuation, grammatical category)</li>
</ul>
<p>Another thing to consider is that the Hansard has a temporal element, meaning we can order the speeches chronologically. We might also be able to use some tricks to investigate how words are used in the context of other words (counting pairs/multiples of words, correlations of words between speeches, graph-based methods, etc…).</p>
<div id="speech-lengths" class="section level4">
<h4>Speech lengths</h4>
<p>We’ll start with the simplest detail relating to the words in our Hansard- how many are used in total each speech.</p>
<p><img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-2-1.png" width="672" /> The vast majority of speeches were at the shorter end of the distribution. The median number of words used was 135, with 75% of speeches using less than 418 words. The top 25% of speeches in terms of word counts range from 418 to almost 1800.</p>
<p>For comparison, take a look at Baroness Smith’s 135 word speech <a href="http://bit.ly/2SaRP80" target="_blank">here</a> and Baroness Stowell’s 420 word speech <a href="http://bit.ly/2SaKh4Z" target="_blank">here</a> for comparison.. Using my internal “speech length” indicator, these results are telling me that 75% of speeches are not really very long at all. Indeed, a 400 word speech only takes 1.5 to 2 minutes to read aloud.</p>
<p>We also know that different MPs used different numbers of speeches. We would expect to see that the more speeches you make, the more words you use. Is this the case?</p>
<div class="figure"><span id="fig:unnamed-chunk-4"></span>
<img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-4-1.png" alt="The relationship between the number of speeches a lord gives and the number of words they use." width="960" />
<p class="caption">
Figure 1: The relationship between the number of speeches a lord gives and the number of words they use.
</p>
</div>
<p>As we might expect, the more speeches you give, the more words you use in total. But this correlation is far from perfect and there is a glaring outlier in the two Lords who made 12 speeches both using hardly any words.</p>
<p>Let’s pick out the peers who made five or more speeches, and look not just at the total number of words, but the number of words used in each of their speeches (to understand the spread).</p>
<div class="figure"><span id="fig:unnamed-chunk-5"></span>
<img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-5-1.png" alt="As above but with specific boxplots for each peer." width="960" />
<p class="caption">
Figure 2: As above but with specific boxplots for each peer.
</p>
</div>
<p>There are clearly different strategies, or perhaps roles, for each different MP. Baroness Hayter makes a similar number of speeches to Tebbit and Hannay, but her speeches are generally longer (none being exceptionally short or long). Lord Taylor, in contrast has an incredibly tight distribution of very short speeches. This is telling- he is in fact the whip of the Conservative party, so his speeches consist exclusively of short rebukes. Lord Howard, a eurosceptic, speaks as a contrarian to many of the amendments moved by other MPs, leading to a large number of short arguments. Lord Bridges, who shows the most variation in speech lengths, was the Government’s secretary for DxEU.</p>
<p>As we can see, even these raw numbers of words tell a story. But now we will move onto…</p>
</div>
<div id="the-text-itself." class="section level4">
<h4>The text itself.</h4>
<p>Boring definitions: Each text is composed of words. People who research <a href="https://en.wikipedia.org/wiki/Text_mining">text mining</a> and apply this in <a href="https://en.wikipedia.org/wiki/Natural_language_processing">natural language processing</a> (NLP) refer to each body of text as a document. Think different newspaper articles, different books by an author. We could treat all of these as documents. <em>Corpus</em> is the word used to refer to a collection of documents. Now let’s think about scale. There are lots of Hansards about Brexit. So we could (and later will) make a corpus of Hansard documents. But here, I have chosen to focus on what can be gleaned from <strong>a single debate</strong>. For our purposes, we will treat <em>speeches</em> as each document, and the corpus will be the collection of speeches in the Hansard.</p>
<pre><code>## # A tibble: 16,340 x 4
##    speech_id word         n speech_total
##        &lt;int&gt; &lt;chr&gt;    &lt;int&gt;        &lt;int&gt;
##  1       106 eu          27          545
##  2       109 euratom     26          480
##  3       244 european    23          225
##  4       148 women       22          566
##  5        32 eu          20          307
##  6       148 rights      20          566
##  7         1 eu          19          437
##  8       124 euratom     19          344
##  9       132 euratom     18          272
## 10       228 devolved    18          409
## # … with 16,330 more rows</code></pre>
<p>The first thing we do is count the number of times each word occurs in each speech, and also the total number of words in each speech. What can we do with this information?</p>
<hr />
</div>
<div id="calculating-the-importance-of-words" class="section level3">
<h3>Calculating the importance of words</h3>
<p>What words are most important in each speech? How can we rank words in terms of importance? Simple questions. Difficult to answer. We’ll go through some examples to understand why defining which words are important to a speech is difficult, and how to get around these problems. But first, here is <em>one way</em> researchers calculate the importance of a word: TF-IDF (Term frequency-Inverse document frequency).</p>
<p>TF-IDF = Term Frequency * Inverse Document Frequency</p>
<p>In our case, this means</p>
<p>TF = (Number of times term appears in speech) / (Total number of terms in the speech) IDF = log_e(Total number of speeches / Number of speeches with term in it)</p>
<p>I explain TF-IDF in detail below, so if you already know what TF-IDF means feel free to skip this bit. If you want a really short and sweet explanation of TF-IDF go to <a href="http://www.tfidf.com/" class="uri">http://www.tfidf.com/</a>.</p>
<hr />
<div id="question" class="section level4">
<h4>Question</h4>
<p>What if we just find the most common words? Surely the words that appear most are the most important?</p>
</div>
<div id="challenge" class="section level4">
<h4>Challenge</h4>
<p>The most common words are just going to be uninformative ones like “the”, “and”, etc…</p>
</div>
<div id="solution" class="section level4">
<h4>Solution</h4>
<p>After counting the frequency of each word in a speech, we can remove <strong>stop words</strong>. This is literally an arbitrary list of “common” words which we have decided not to include in the analysis and remove. It’s not flashy, but it’s useful for what we’re doing here and is how I got counts in the table above.</p>
<p>Counting the frequency of words gives us what researchers call the “<strong>term frequency</strong>” for a document.</p>
<hr />
</div>
<div id="question-1" class="section level4">
<h4>Question</h4>
<p>Now we have counts of informative words, aren’t the most common ones the most important?</p>
</div>
<div id="challenge-1" class="section level4">
<h4>Challenge</h4>
<p>Maybe. Earlier in the article we showed that speeches are of different lengths. A word which is used 50 times must be important, you might say? What if this was in a 50,000 word document? Probably not so important.</p>
</div>
<div id="solution-1" class="section level4">
<h4>Solution</h4>
<p>We divide the frequency of each word by the total number of words in that speech. If we didn’t normalise like this, when we try to compare the most important words between speeches, words from longer speeches would end up outranking words from shorter ones, even though they might proportionally have been used less.</p>
<hr />
</div>
<div id="question-2" class="section level4">
<h4>Question</h4>
<p>We’ve calculated the “normalised term frequency”. What on earth else is needed to tell us what the important words are?</p>
</div>
<div id="challenge-2" class="section level4">
<h4>Challenge</h4>
<p>What do we actually mean by <em>important</em>? Imagine you have a set of newspapers articles about education. The word “school” and “teacher” probably appears in every document (with varying frequency), so we could penalise these words allowing other words that distinguish different speeches to be found. We could just remove these words that are shared between documents (treat them as “stop words”). But there is a better solution.</p>
</div>
<div id="solution-2" class="section level4">
<h4>Solution</h4>
<p>When we have our <strong>term frequency</strong>, we can multiply this by the <strong>“Inverse document frequency”</strong> for that word. How do we calculate this? Say you have 10 documents. You’re word appears in 8 of them (it’s a pretty common word). The inverse document frequency is equal to <code>log(10/8)</code>. Let’s compare how this changes if we make our word rarer amongst the documents.</p>
<pre><code>## # A tibble: 6 x 4
##   `Word in X docume… `Total number of … `Inverse document f… `Unlogged IDF`
##                &lt;dbl&gt;              &lt;dbl&gt;                &lt;dbl&gt;          &lt;dbl&gt;
## 1                  8                 10                0.223           1.25
## 2                  8                100                2.53           12.5 
## 3                  8               1000                4.83          125   
## 4                  8              10000                7.13         1250   
## 5                  8             100000                9.43        12500   
## 6                  8            1000000               11.7        125000</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-8"></span>
<img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-8-1.png" alt="If a word appears in 8 documents, how does the IDF change as we increase the number of documents?" width="672" />
<p class="caption">
Figure 3: If a word appears in 8 documents, how does the IDF change as we increase the number of documents?
</p>
</div>
<p>The unlogged IDF shown for comparison. We just log the value so that this “IDF multiplier” stays within a reasonable range- the IDF increases in a linear way as the number of documents increases by orders of magnitude.</p>
<p>That aside, as documents containing our word become <em>rarer</em>, the word’s IDF score <em>increases</em>. This is the important thing. Think about what this means:</p>
<p>TF-IDF (“Word importance”) = Term frequency * Inverse Document Frequency</p>
<p>More frequent terms get a higher score (good). Words that appear in a smaller fraction of documents get a higher score (also good). So if a word is unique to a speech and is used in it often, it gets a high score, because it defines that speech and not others. Low scoring words are either not used a lot in any speeches, or appear in almost every document- meaning they can’t be used to accurately define any of them.</p>
<hr />
</div>
<div id="tf-idf-for-the-longest-speeches" class="section level4">
<h4>TF-IDF for the longest speeches</h4>
<p>Let’s take the six longest speeches, and which words were picked out as the most important ones.</p>
<div class="figure"><span id="fig:unnamed-chunk-9"></span>
<img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-9-1.png" alt="The words are on the y axis and their TF-IDF is the position of each bar on the x axis. Each panel is a different speech." width="960" />
<p class="caption">
Figure 4: The words are on the y axis and their TF-IDF is the position of each bar on the x axis. Each panel is a different speech.
</p>
</div>
<p>Looks messy, let’s talk it through. Generally, TF-IDF seems to have pulled out words that are important in these speeches ranked in the top 10. There are also words that are important but won’t make sense without further context (speech 1 has it’s top word as “drink” because the peer mentions the “food and drink federation” repeatedly). Other words seem to not have the “right” rank if we were to do it ourselves intuitively. Finally, there are words with a high TF-IDF that aren’t representative of the speech at all (“romans” doesn’t really tell us anything about speech 152). But in general, we can see that speech 148 is about womens rights, 109 about Euratom and nuclear safety and 228 about the role of devolved administrations. 1 and 106 are less clear but seem to be about fair rights for EU nationals and UK citizens. Speech 152 seems a bit unclear and no one word has a particularly high TF-IDF anyway.</p>
<hr />
<p><em>As a complete and inconsequential aside before we move on</em>, here are the top 10 TF-IDF scores from every speech in rank order from most important to least important.</p>
<pre><code>## # A tibble: 10 x 6
##    speech_id word                 n     tf   idf tf_idf
##        &lt;int&gt; &lt;chr&gt;            &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1       212 bullet               4 0.0571  4.78  0.273
##  2        16 minorities           7 0.0778  3.39  0.264
##  3       245 bodies              11 0.0753  3.17  0.239
##  4       218 honourable           3 0.0577  3.39  0.196
##  5       130 funding              6 0.0612  2.99  0.183
##  6       216 insurmountable       2 0.0377  4.78  0.180
##  7       118 nhs                  4 0.0635  2.83  0.180
##  8       184 constitutionally     3 0.0429  4.09  0.175
##  9       184 improper             3 0.0429  4.09  0.175
## 10       115 cumbrian             2 0.0364  4.78  0.174</code></pre>
<p>I’ll put it down to the absurdity of the universe that “bullet”, “minorities” and “bodies” appeared as the top three most important words, and try not to worry too much about it.</p>
<hr />
</div>
<div id="hansard-timeline-using-tf-idf" class="section level4">
<h4>Hansard timeline using TF-IDF</h4>
<p>We are going to use TF-IDF as a way to summarise texts. We have seen how this is like pulling important words from a “bag of words” (each speech). The meaning from the context which the words were used in is inevitably lost, but it’s a useful heuristic and the way TF-IDF is calculated is transparent (not a black box).</p>
<p>Below is a pretty cool graphic (<strong>Open it in a new tab!</strong>), where I’ve extracted the word with the largest TF-IDF from each speech longer than 50 (non-stop-word) words and displayed them chronologically. The size of the word represents its TF-IDF.</p>
<div class="figure"><span id="fig:unnamed-chunk-11"></span>
<img src="/post/2019-02-05-text-mining-the-eu-withdrawal-bill-hansard_files/figure-html/unnamed-chunk-11-1.png" alt="The position of words on the y axis is irrelevant! Cheers to Kamil Slowikowski (https://slowkow.com/) for making ggrepel which organises the text so nicely." width="1440" />
<p class="caption">
Figure 5: The position of words on the y axis is irrelevant! Cheers to Kamil Slowikowski (<a href="https://slowkow.com/" class="uri">https://slowkow.com/</a>) for making ggrepel which organises the text so nicely.
</p>
</div>
<p>Early on in the debate, there’s lots of talk about “citizens”. Then there is a period of debate about nuclear bodies/Euratom. Then a period where lots of industries and issues are mentioned including education, fishing, the NHS and women’s rights. The rest of the debate is largely about Parliamant’s role in the decisions made by the government, and the assurances for devolved administrations.</p>
<p>So TF-IDF is a pretty cool method for finding out the most important words in a text. But what are some problems with it? You might already have noticed some.</p>
<ul>
<li>If a word in few documents is used often in a text -even if it does <strong>not represent the text at all</strong>- it will be promoted to the highest TF-IDF (look at “Romans” above).</li>
<li>In light of this idea of “representativeness” of the high scoring words, TF-IDF is what we call a <strong>bag of words</strong> method for analysing text. We have just taken all the words and counted them. In doing this, we ignore the context which words are used in. We ignore the semantics of the sentence. A more nuanced summary is difficult to achieve using TF-IDF alone.</li>
<li>Shorter texts suffer from the fact that no ‘interesting’ words occur frequently, so we’re more likely to get unrepresentative words scoring high TF-IDFs. Similarly, how much do we trust a word with a term frequency of 2 which has scored highly because the text was short and it occured in very few documents?</li>
</ul>
</div>
</div>
<div id="conclusions" class="section level3">
<h3>Conclusions</h3>
<p>In this article, we have explored how simply counting the number of words in speeches can reveal things about a Hansard. We talked in detail about how we can use these counts to create a useful scoring system (TF-IDF) for finding important words in documents, culminating in a summarised timeline of topics discussed in the Hansard. We also talked about the limitations of this method. But this is barely scratching the surface of what can be achieved using text mining. More advanced methods are available, and the amount you can learn using simpler techniques can often be extended if you apply them more creatively. Next time we will discuss how ideas like bigrams, regular expressions searches, sentiment analysis, latent dirichlet allocation and more can be used to glean information from the Hansard.</p>
</div>
</div>
