---
title: Books I've read
author: Matt Chaib
date: '2019-02-04'
slug: read-books
categories:
  - Books I've Read
tags:
  - books
---

# Sci-fi/Dystopian/Fantasy

- Greybeard, Brian Aldiss
- The Gods Themselves, Isaac Asimov
- The Last Question, Isaac Asimov
- The Body Snatchers, Jack Finney
- The Dispossessed, Ursula Le Guin
- The Word for World is Forest, Ursula Le Guin
- Brave New World, Aldous Huxley
- Flowers for Algernon, Daniel Keyes
- Ringworld, Larry Niven (current)
- 1984, George Orwell
- The Long Earth, Terry Pratchett/Steven Baxter
- Roadside Picnic, Boris and Arkady Strugatsky
- Hard to be a God, Boris and Arkady Strugatsky
- The Man Who Fell to Earth, Walter Tevis
- The Martian, Andy Weir
- The Island of Doctor Moreau, H.G Wells
- The Fifth Head of Cerberus, Gene Wolfe
- The Day of the Triffids, John Wyndham

# Terry Pratchett

- The Colour of Magic
- The Light Fantastic
- Equal Rites
- Mort
- Pyramids
- Small Gods
- Night Watch
- Going Postal
- Making Money
- Good Omens (with Neil Gaiman)

# Non-fiction

- The Gene, An Intimate History, Siddhartha Mukherjee
- Lands of Charm and Cruelty, Stan Sesser
- Weapons of Math Destruction, Cathy O'Neil
- Out of Sight, Out of Mind, John Podmore
- The Truth in Small Doses, Clifton Leaf*
- The Eigth Day of Revolution, Horace Judson (current)
- What Mad Pursuit, Francis Crick
- Mindstorms, Seymour Papert
- The Future of Ideas, Lawrence Lessig
- Creative Schools, Ken Robinson
- Miseducation, Diane Reay
- Once Upon a Distant War, William Prochnau (current)
- Underground, Haruki Murakami
- The Snow Leopard, Peter Matthiessen
- Pedagogy of the Oppressed, Paulo Freire*
- Humanising the Economy, John Restakis*

